Removed azure-pipeline npm build

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -8,7 +8,11 @@ ARG CACHE_INVALIDATOR=1
 
 ENV BUILD_MODE=$BUILD_MODE
 
+# Debugging info
+RUN ls -al ./
+RUN cat .env.$BUILD_MODE || echo "⚠️ Env file missing!"
 RUN echo "BUILD_MODE = $BUILD_MODE"
+
 COPY package.json package-lock.json ./
 RUN npm install
 
